app = "meu-bot-telegram"
primary_region = "gru"  # (região Brasil; pode trocar pra mia, ewr, etc)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "true"

[processes]
  app = "python bot.py"
