app = "amigo-do-eric-bot-telegram"  # pode deixar igual ao Fly.io
primary_region = "gru"               # região Brasil
[build]
  builder = "paketobuildpacks/builder:base"
[env]
  PYTHONUNBUFFERED = "true"
[processes]
  app = "python bot.py"
